# Generated by Django 4.1 on 2022-08-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctori', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='static/images/logo_profile_doc.jpg', upload_to='images/doctori/'),
        ),
    ]
