# Generated by Django 4.1 on 2022-08-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_serviciu', models.CharField(max_length=50)),
                ('pret_serviciu', models.IntegerField()),
                ('detalii', models.CharField(blank=True, max_length=100)),
                ('durata', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
