# Generated by Django 4.1 on 2022-09-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preturi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pret',
            name='pret_serviciu',
            field=models.CharField(max_length=50),
        ),
    ]
